[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "agentic-research-assistant"
version = "0.1.0"
description = "Agentic RAG Research Assistant using LangGraph, ChromaDB, Groq, and Streamlit"
readme = "README.md"
requires-python = ">=3.10"

authors = [
    { name = "prvsh24X7" }
]

dependencies = [
    "streamlit==1.44.1",
    "langgraph",
    "langchain",
    "langchain-core",
    "langchain-community",
    "langchain-groq",
    "chromadb",
    "sentence-transformers",
    "pydantic",
    "fastapi",
    "uvicorn",
    "python-dotenv",
    "tqdm",
    "sqlite-utils"
]


[tool.setuptools]
packages = ["src"]


[tool.streamlit]
server.fileWatcherType = "none"


[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort"
]